version: '3.4'

services:
  clientKnowledgeDump:
    image: client-knowledge-dump
    build:
      context: Client/knowledge-dump
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
